name: dev-version

on:
  workflow_call:
    outputs:
      version:
        description: Calculated version
        value: ${{ jobs.version.outputs.version }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  version:
    runs-on: ubuntu-latest
    name: Calculate Dev Version
    steps:
      - id: version
        name: Calculate build version
        run: |
          GH_VERSION=$(gh release list --repo UnstoppableMango/pulumi-commandx --exclude-drafts --exclude-pre-releases --limit 1)
          # Get latest stable release. Return only first column from result (tag).
          LAST_VERSION=$(echo "${GH_VERSION}" | cut -f1)
          # Use semver NPM CLI tool to find next minimal version
          NEXT_VERSION=$(npx -y semver --increment patch "${LAST_VERSION}")
          # Include an always-increasing number to order correctly
          TIMESTAMP=$(date +%s)
          # Indicate the commit the build came from
          SHORTHASH=$(echo "${GITHUB_SHA}" | cut -c1-8)
          # Combine all version components together
          VERSION=${NEXT_VERSION}-alpha.${TIMESTAMP}+${SHORTHASH}
          echo "${VERSION}"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
